version: "3.9"

services:

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 30 
      start_period: 30s
    networks:
      - pipeline-net

  pipeline:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql # service name = hostname in Docker network
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    volumes:
      - .:/app
      # Optional: mount logs & data folders if you want persistence outside container
      # - ./logs:/app/logs
      # - ./data:/app/data
    command: [ "python", "-m", "src.pipeline" ]
    networks:
      - pipeline-net

volumes:
  mysql-data:


networks:
  pipeline-net:
    driver: bridge
